/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'reports' : bigint,
  'postId' : bigint,
}
export type ExternalBlob = Uint8Array;
export type ModerationStatus = { 'active' : null } |
  { 'blocked' : string } |
  { 'flagged' : string };
export interface Post {
  'id' : bigint,
  'content' : string,
  'video' : [] | [ExternalBlob],
  'author' : Principal,
  'timestamp' : bigint,
  'reports' : bigint,
  'image' : [] | [ExternalBlob],
}
export interface PostPage {
  'nextPageStart' : [] | [bigint],
  'posts' : Array<Post>,
}
export interface Profile {
  'bio' : string,
  'username' : string,
  'preferences' : string,
  'isAdult' : boolean,
}
export type ReactionType = { 'sad' : null } |
  { 'angry' : null } |
  { 'like' : null } |
  { 'love' : null } |
  { 'laugh' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllCommentReports' : ActorMethod<[], undefined>,
  'clearAllPostReports' : ActorMethod<[], undefined>,
  'clearCommentReports' : ActorMethod<[bigint], boolean>,
  'clearFlaggedPost' : ActorMethod<[bigint], boolean>,
  'clearPostReports' : ActorMethod<[bigint], boolean>,
  'createComment' : ActorMethod<[bigint, string], bigint>,
  'createPost' : ActorMethod<
    [string, [] | [ExternalBlob], [] | [ExternalBlob]],
    bigint
  >,
  'deleteComment' : ActorMethod<[bigint], boolean>,
  'deletePost' : ActorMethod<[bigint], boolean>,
  'getBlockedPosts' : ActorMethod<[], Array<bigint>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComment' : ActorMethod<[bigint], [] | [Comment]>,
  'getContentGuidelines' : ActorMethod<[], string>,
  'getFlaggedHateSpeechPosts' : ActorMethod<
    [],
    Array<[bigint, ModerationStatus]>
  >,
  'getModerationStatus' : ActorMethod<[bigint], ModerationStatus>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getPostComments' : ActorMethod<[bigint], Array<Comment>>,
  'getPostsPage' : ActorMethod<[bigint, bigint], PostPage>,
  'getReportedComments' : ActorMethod<[], Array<Comment>>,
  'getReportedCommentsAdminView' : ActorMethod<[], Array<Comment>>,
  'getReportedPosts' : ActorMethod<[], Array<Post>>,
  'getReportedPostsAdminView' : ActorMethod<[], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getUsernameFromPrincipal' : ActorMethod<[Principal], [] | [string]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserAdult' : ActorMethod<[Principal], boolean>,
  'manualBlockPost' : ActorMethod<[bigint], boolean>,
  'removeCommentReaction' : ActorMethod<[bigint], undefined>,
  'removePostReaction' : ActorMethod<[bigint], undefined>,
  'reportComment' : ActorMethod<[bigint], boolean>,
  'reportPost' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'setCommentReaction' : ActorMethod<[bigint, ReactionType], undefined>,
  'setPostReaction' : ActorMethod<[bigint, ReactionType], undefined>,
  'unblockPost' : ActorMethod<[bigint], boolean>,
  'updateComment' : ActorMethod<[bigint, string], boolean>,
  'updatePost' : ActorMethod<
    [bigint, string, [] | [ExternalBlob], [] | [ExternalBlob]],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];