/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'reports' : bigint,
  'postId' : bigint,
}
export interface Image { 'data' : Uint8Array, 'mimeType' : string }
export interface Post {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'reports' : bigint,
  'image' : [] | [Image],
}
export interface Profile {
  'bio' : string,
  'username' : string,
  'preferences' : string,
  'isAdult' : boolean,
}
export type ReactionType = { 'sad' : null } |
  { 'angry' : null } |
  { 'like' : null } |
  { 'love' : null } |
  { 'laugh' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCommentReports' : ActorMethod<[bigint], boolean>,
  'clearPostReports' : ActorMethod<[bigint], boolean>,
  'createComment' : ActorMethod<[bigint, string], bigint>,
  'createPost' : ActorMethod<[string, [] | [Image]], bigint>,
  'deleteComment' : ActorMethod<[bigint], boolean>,
  'deletePost' : ActorMethod<[bigint], boolean>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComment' : ActorMethod<[bigint], [] | [Comment]>,
  'getContentGuidelines' : ActorMethod<[], string>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getPostComments' : ActorMethod<[bigint], Array<Comment>>,
  'getReportedComments' : ActorMethod<[], Array<Comment>>,
  'getReportedPosts' : ActorMethod<[], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getUsernameFromPrincipal' : ActorMethod<[Principal], [] | [string]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserAdult' : ActorMethod<[Principal], boolean>,
  'removeCommentReaction' : ActorMethod<[bigint], undefined>,
  'removePostReaction' : ActorMethod<[bigint], undefined>,
  'reportComment' : ActorMethod<[bigint], boolean>,
  'reportPost' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'setCommentReaction' : ActorMethod<[bigint, ReactionType], undefined>,
  'setPostReaction' : ActorMethod<[bigint, ReactionType], undefined>,
  'updateComment' : ActorMethod<[bigint, string], boolean>,
  'updatePost' : ActorMethod<[bigint, string, [] | [Image]], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];