/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Image = IDL.Record({
  'data' : IDL.Vec(IDL.Nat8),
  'mimeType' : IDL.Text,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'reports' : IDL.Nat,
  'image' : IDL.Opt(Image),
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'preferences' : IDL.Text,
  'isAdult' : IDL.Bool,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'reports' : IDL.Nat,
  'postId' : IDL.Nat,
});
export const ReactionType = IDL.Variant({
  'sad' : IDL.Null,
  'angry' : IDL.Null,
  'like' : IDL.Null,
  'love' : IDL.Null,
  'laugh' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCommentReports' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'clearPostReports' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'createComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Opt(Image)], [IDL.Nat], []),
  'deleteComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComment' : IDL.Func([IDL.Nat], [IDL.Opt(Comment)], ['query']),
  'getContentGuidelines' : IDL.Func([], [IDL.Text], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getPostComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getReportedComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'getReportedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getUsernameFromPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserAdult' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'removeCommentReaction' : IDL.Func([IDL.Nat], [], []),
  'removePostReaction' : IDL.Func([IDL.Nat], [], []),
  'reportComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'reportPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'setCommentReaction' : IDL.Func([IDL.Nat, ReactionType], [], []),
  'setPostReaction' : IDL.Func([IDL.Nat, ReactionType], [], []),
  'updateComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updatePost' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(Image)], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Image = IDL.Record({
    'data' : IDL.Vec(IDL.Nat8),
    'mimeType' : IDL.Text,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'reports' : IDL.Nat,
    'image' : IDL.Opt(Image),
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'preferences' : IDL.Text,
    'isAdult' : IDL.Bool,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'reports' : IDL.Nat,
    'postId' : IDL.Nat,
  });
  const ReactionType = IDL.Variant({
    'sad' : IDL.Null,
    'angry' : IDL.Null,
    'like' : IDL.Null,
    'love' : IDL.Null,
    'laugh' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCommentReports' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'clearPostReports' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'createComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Opt(Image)], [IDL.Nat], []),
    'deleteComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComment' : IDL.Func([IDL.Nat], [IDL.Opt(Comment)], ['query']),
    'getContentGuidelines' : IDL.Func([], [IDL.Text], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getPostComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getReportedComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'getReportedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getUsernameFromPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserAdult' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'removeCommentReaction' : IDL.Func([IDL.Nat], [], []),
    'removePostReaction' : IDL.Func([IDL.Nat], [], []),
    'reportComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'reportPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'setCommentReaction' : IDL.Func([IDL.Nat, ReactionType], [], []),
    'setPostReaction' : IDL.Func([IDL.Nat, ReactionType], [], []),
    'updateComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updatePost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(Image)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };